spring:
  application.name: "delivery-food-system"
  web:
    error:
      include-message: always
      include-binding-errors: always

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      properties.spring.json.trusted.packages: com.foodtakeway.codechallenge.examples.event
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: "consumer-group"
      auto-offset-reset: earliest
    bootstrap-servers: "localhost:9092"

  data:
    mongodb:
      uri: "mongodb://localhost:27017/mongodatabase"