spring:
  application:
    name: delivery-food-system

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:consumer-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  web:
    error:
      include-message: always
      include-binding-errors: always
  mongodb:
    representation:
      uuid: standard
    uri: ${MONGODB_URI:mongodb://localhost:27017/mongodatabase}

discount:
  percentage: 0.10
  threshold: 100.0
